### PR TITLE
Fix welcome route

### LINKED ISSUE #273: Fix home route
Home route redirects to a page that is not used by the app.

### PR DESCRIPTION
**Pull request by NatsGt**
# Description

Set welcome page to the home route "/"

Fixes #273 

# How to test?

npm run dev http://localhost:3000/

# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented my code, particularly in hard-to-understand areas, if you code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if you code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

**Review by senner007 — CHANGES_REQUESTED** [review]
This won't work properly. You can't go to welcome after login

Instead if you revert the commit and change the contents Home Component to this
```

import React from 'react';
import { BrowserRouter as Router, Route, Switch, Redirect } from 'react-router-dom';

export const Home = () => <Redirect to='/welcome'  />
```

**Comment by senner007** [comment]
> This won't work properly. You can't go to welcome after login
> 
> Instead if you revert the commit and change the contents Home Component to this
> 
> ```
> 
> import React from 'react';
> import { BrowserRouter as Router, Route, Switch, Redirect } from 'react-router-dom';
> 
> export const Home = () => <Redirect to='/welcome'  />
> ```

or /profile

File: src/client/containers/Home/Home.js [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable no-unused-vars */
 import React from 'react';
+import { BrowserRouter as Router, Redirect } from 'react-router-dom';
 
-export const Home = () => <section className="home">Final project!</section>;
+export const Home = () => <Redirect to="/welcome" />;
```
Comment (senner007) [inline src/client/containers/Home/Home.js]: better make it /profile
Then it won't jump to welcome page if you are already logged in

**Review by senner007 — CHANGES_REQUESTED** [review]

**Review by senner007 — APPROVED** [review]
✔

**Comment by senner007** [comment]
@NatsGt 
Build fail. Remove the Home.test

**Review by senner007 — APPROVED** [review]
✔
Good :)
Now it only has the migration fail
