### PR TITLE
Fix: addMember function to detect role automatically

### LINKED ISSUE #247: Backend: fix addMember function in users.controller
Currently, the function adds only members with role 'basic', which is hardcoded. 

need to refactor it and introduce the role parameter, so it could be passed to the endpoint.

### PR DESCRIPTION
**Pull request by shpomp**
# Description

addMember function in users.controller is changed to automatically detect the member role according to the parameters that are passed to the POST endpoint. 

Fixes #247 

# How to test?

npm run dev and test in swagger docs. 
http://localhost:5000/api/documentation/#/Members/post_users__userId__boards__boardId__members__memberId_
 
# Checklist

- [x] I have performed a self-review of my own code
- [x] I have followed the name conventions for CSS Classnames and filenames, Components names and filenames, Style filenames, if you are in doubt check the project README.MD and here https://github.com/HackYourFuture-CPH/curriculum/blob/master/review/review-checklist.md
- [x] I have commented on my code, particularly in hard-to-understand areas, if your code was simple enough mark the box anyway
- [x] I have made corresponding changes to the documentation, if your code was simple enough mark the box anyway
- [x] This PR is ready to be merged and not breaking any other functionality

### CODE REVIEW

File: src/server/api/controllers/members.controller.js [hunk 1]
```diff
@@ -57,10 +57,12 @@ const addMember = async (userId, boardId, memberId) => {
   }
   await userIsOwner(userId, boardId);
 
+  const role = userId === memberId ? 'owner' : 'basic';
```
Comment (senner007) [inline src/server/api/controllers/members.controller.js:60]: With this change, the owner is not added when the board is created

**Review by senner007 — CHANGES_REQUESTED** [review]

File: src/server/api/controllers/members.controller.js (hunk 1 above)
Comment (shpomp) [reply src/server/api/controllers/members.controller.js:60]: ohhhhhhh 🤦🏽 
Yeah. I will make a new issue and PR to change the AddMember logic a bit.

Comment (senner007) [reply src/server/api/controllers/members.controller.js:60]: Its okay to do it from here, imo.
Since its related to this

Comment (shpomp) [reply src/server/api/controllers/members.controller.js:60]: I think now with changes of AddMember page #251  all should be good 🙏🏽

**Review by senner007 — APPROVED** [review]
✔
